name = "zenvioo"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "zenvioo.com/*", zone_name = "zenvioo.com" }
]

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "zenvioo-storage"

[vars]
NODE_ENV = "production"
